<?php

?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="<?php echo $_layoutRutas['ruta_img'];?>favicon.ico" />
	<title>.::Gigpz la web de tus Ideas::.</title>
	<link href="<?php echo BASE_URL;?>public/css/bootstrap.min.css" rel="stylesheet">
	<link href="<?php echo BASE_URL;?>public/css/nivo-slider.css" media="screen" rel="stylesheet" />
	<!--<meta http-equiv="Content-Type" Content="text/html; charset=utf8" />-->
	<link rel="stylesheet" type="text/css" href="<?php echo $_layoutRutas['ruta_css']; ?>estilos.css" />
	<!--<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js" type="text/javascript"></script>-->
	<script type="text/javascript" src="<?php echo BASE_URL; ?>public/js/jquery-min.js"></script>
	<script src="<?php echo BASE_URL; ?>public/js/bootstrap.min.js"></script>
	<script src="<?php echo BASE_URL; ?>public/js/jquery.nivo.slider.pack.js"></script>
	<script type="text/javascript" src="<?php echo $_layoutRutas['ruta_js']; ?>funciones.js"></script>
	<script type="text/javascript">
		$(window).load(function() {
	         $('#slider').nivoSlider({
	            //effect: 'random', // Specify sets like: 'fold,fade,sliceDown'
	            effect: 'random',
	            slices: 15, // For slice animations
	            boxCols: 8, // For box animations
	            boxRows: 4, // For box animations
	            animSpeed: 500, // Slide transition speed
	            pauseTime: 3000, // How long each slide will show
	            startSlide: 0, // Set starting Slide (0 index)
	            directionNav: false, // Next & Prev navigation
	            controlNav: false, // 1,2,3... navigation
	            controlNavThumbs: false, // Use thumbnails for Control Nav
	            pauseOnHover: true, // Stop animation while hovering
	            manualAdvance: false, // Force manual transitions
	            prevText: '', // Prev directionNav text
	            nextText: '', // Next directionNav text
	            randomStart: true
	         });	       
	    });
	</script>
</head>
<body onload="">
	<!--like box-->
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>
	<!--facebook-->


