<!DOCTYPE html>
<html lang="en">
<head>
<title>..::Gigpz::..</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="<?php echo gigpzModel::URL();?>public/img/favicon.png" />
<!--<link rel="shortcut icon" href="<?php echo gigpzModel::URL();?>/public/img/favicon.ico" />-->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="expires" content="-1" />

<!--<link href="<php echo gigpzModel::URL();?>public/css/bootstrap.min.css" rel="stylesheet">-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
<link href="<?php echo gigpzModel::URL();?>public/css/ui/jquery-ui.css" rel="stylesheet">

<link href="<?php echo gigpzModel::URL();?>public/css/docs.min.css" rel="stylesheet">
<link href="<?php echo gigpzModel::URL();?>public/css/nivo-slider.css" rel="stylesheet" type="text/css" />

<link href="<?php echo gigpzModel::URL();?>views/layouts/gigpz/css/estilos.css" rel="stylesheet" type="text/css" />
<!--<link href="<php echo gigpzModel::URL();?>views/layouts/gigpz/css/estilos.less" rel="stylesheet/less" type="text/css"/>-->
<!--<link href="public/css/carousel.css" rel="stylesheet">-->
</head>
<body>
	<!--like box-->
	<!--<div id="fb-root"></div>
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>-->
	<!--facebook-->
	
	<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><?php echo APP_COMPANY;?></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <!--<ul class="nav navbar-nav navbar-right">
            <li><a href="#">El Mundo</a></li>
            <li><a href="#">Blog</a></li>
            <li><a href="#">Configuracion</a></li>
            <li><a href="#">Salir</a></li>
          </ul>-->
          <!--<form class="navbar-form navbar-right">
          	<div class="input-group">
            <input type="text" class="form-control input-sm" placeholder="...">
        	</div>
          </form>-->
        </div>
      </div>
    </nav>
    <br><br><br>
	<div class="container-fluid" id="contenedor"> <!--abarca el 100%-->
		<img src="<?php echo gigpzModel::URL();?>public/img/logoGz.png">

	</div> <!--fin contenedor-->
	<footer>
		<div class="container-fluid">
			<h4><span class="icon-twitter3" title="twitter"></span><span class="icon-facebook3" title="facebook"></span><span class="icon-youtube3" title="youtube"></span></h4>
			<h5>Copyright &copy; 2015 - www.gigpz.com</h5>
		</div>
	</footer>
	<script type="text/javascript"></script>
	<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
	<!--<script src="<php echo gigpzModel::URL();?>public/js/bootstrap.min.js"></script>-->
	<script src="<?php echo gigpzModel::URL();?>public/js/ie10-viewport-bug-workaround.js"></script>
	<script src="<?php echo gigpzModel::URL();?>public/js/unslider.min.js"></script>
	<!-- Optional theme -->
	<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">-->
	<script src="<?php echo gigpzModel::URL();?>public/js/jquery.nivo.slider.pack.js" type="text/javascript"></script>
	<script src="<?php echo gigpzModel::URL();?>public/js/ui/jquery-ui.js"></script>
	<script src="<?php echo gigpzModel::URL();?>public/js/ie-emulation-modes-warning.js"></script>
	
	<script src="<?php echo gigpzModel::URL();?>public/js/md5.js"></script>
	<script src="<?php echo gigpzModel::URL();?>views/layouts/gigpz/js/funciones.js"></script>
	<script type="text/javascript">
    $(document).ready(function() {
        //limpiarForms();
    });

    $(window).load(function() {
    		$('#slider').nivoSlider({
    			 	effect: 'random',                 // Specify sets like: 'fold,fade,sliceDown'
				    slices: 15,                     // For slice animations
				    boxCols: 8,                     // For box animations
				    boxRows: 4,                     // For box animations
				    animSpeed: 500,                 // Slide transition speed
				    pauseTime: 3000,                 // How long each slide will show
				    startSlide: 0,                     // Set starting Slide (0 index)
				    directionNav: false,             // Next & Prev navigation
				    controlNav: false,                 // 1,2,3... navigation
				    controlNavThumbs: false,         // Use thumbnails for Control Nav
				    pauseOnHover: true,             // Stop animation while hovering
				    manualAdvance: false,             // Force manual transitions
				    prevText: '',                 // Prev directionNav text
				    nextText: '',                 // Next directionNav text
				    randomStart: false,             // Start on a random slide
				    beforeChange: function(){},     // Triggers before a slide transition
				    afterChange: function(){},         // Triggers after a slide transition
				    slideshowEnd: function(){},     // Triggers after all slides have been shown
				    lastSlide: function(){},         // Triggers when last slide is shown
				    afterLoad: function(){}         // Triggers when slider has loaded
    		});
	});

	$(function() {
		   $(".draggable").draggable({
		   	revert: true,
		   	scroll: true,
		   	cursor: "move"
		   });		   
		   $("#droppable").droppable({
		   		accept: ".draggable",
				//tolerance: "touch",
				tolerance: "pointer",
		     	drop: function( event, ui ) {
		     	//alert("Eliminar Columna1.0");
		        //$("#"+_columActivo).draggable("destroy");
		        idcol = $("#"+_columActivo).attr("attr");
		        $("#"+_columActivo).remove();
		        eliminarColumna(idcol);
		      }
		    });
		    //$(".draggable").draggable();
		    /*$(".droppable").droppable({
		      drop: function( event, ui ) {
		        $(this).addClass("droppable").find("p").html("Dropped!");
		      }
		    });*/
	});
  	</script>
</body>
</html>